#!/bin/bash

if [[ -z $smlpath ]]
then
	path="/home/efx/Development/PHD/Airi/current/webots"
else
	path="$smlpath/current/webots"
fi

prefix="wavy2"

conf="articleFrontier_$prefix"
template="template_systematicHybridStudy5.xml"
settings="current.xml"

cpg_interneurons3_3FBL_minfdb1.txt

	prefix="3FBL_minfdb1"
	echo "Extracting hybrid study on $prefix"
	set_path=$path/conf_$conf/settings/$settings
	cp $path/conf_$conf/settings/$template $path/conf_$conf/settings/$settings
	find $set_path | xargs perl -pi -e "s/\|CONF\|/$conf/g"
	find $set_path | xargs perl -pi -e "s/\|PREFIX\|/$prefix/g"
	webots_loadlib -s $settings -c $conf

	prefix="3FBL_mincpg1"
	echo "Extracting hybrid study on $prefix"
	set_path=$path/conf_$conf/settings/$settings
	cp $path/conf_$conf/settings/$template $path/conf_$conf/settings/$settings
	find $set_path | xargs perl -pi -e "s/\|CONF\|/$conf/g"
	find $set_path | xargs perl -pi -e "s/\|PREFIX\|/$prefix/g"
	webots_loadlib -s $settings -c $conf

	prefix="3FBL_oscAnkle"
	echo "Extracting hybrid study on $prefix"
	set_path=$path/conf_$conf/settings/$settings
	cp $path/conf_$conf/settings/$template $path/conf_$conf/settings/$settings
	find $set_path | xargs perl -pi -e "s/\|CONF\|/$conf/g"
	find $set_path | xargs perl -pi -e "s/\|PREFIX\|/$prefix/g"
	webots_loadlib -s $settings -c $conf

	prefix="3FBL_oscAnkle1"
	echo "Extracting hybrid study on $prefix"
	set_path=$path/conf_$conf/settings/$settings
	cp $path/conf_$conf/settings/$template $path/conf_$conf/settings/$settings
	find $set_path | xargs perl -pi -e "s/\|CONF\|/$conf/g"
	find $set_path | xargs perl -pi -e "s/\|PREFIX\|/$prefix/g"
	webots_loadlib -s $settings -c $conf

	prefix="3FBL_oscAnkle2"
	echo "Extracting hybrid study on $prefix"
	set_path=$path/conf_$conf/settings/$settings
	cp $path/conf_$conf/settings/$template $path/conf_$conf/settings/$settings
	find $set_path | xargs perl -pi -e "s/\|CONF\|/$conf/g"
	find $set_path | xargs perl -pi -e "s/\|PREFIX\|/$prefix/g"
	webots_loadlib -s $settings -c $conf


	prefix="3FBL_oscHip"
	echo "Extracting hybrid study on $prefix"
	set_path=$path/conf_$conf/settings/$settings
	cp $path/conf_$conf/settings/$template $path/conf_$conf/settings/$settings
	find $set_path | xargs perl -pi -e "s/\|CONF\|/$conf/g"
	find $set_path | xargs perl -pi -e "s/\|PREFIX\|/$prefix/g"
	webots_loadlib -s $settings -c $conf

	prefix="3FBL_oscKnee"
	echo "Extracting hybrid study on $prefix"
	set_path=$path/conf_$conf/settings/$settings
	cp $path/conf_$conf/settings/$template $path/conf_$conf/settings/$settings
	find $set_path | xargs perl -pi -e "s/\|CONF\|/$conf/g"
	find $set_path | xargs perl -pi -e "s/\|PREFIX\|/$prefix/g"
	webots_loadlib -s $settings -c $conf

	prefix="3FBL_oscBiArt"
	echo "Extracting hybrid study on $prefix"
	set_path=$path/conf_$conf/settings/$settings
	cp $path/conf_$conf/settings/$template $path/conf_$conf/settings/$settings
	find $set_path | xargs perl -pi -e "s/\|CONF\|/$conf/g"
	find $set_path | xargs perl -pi -e "s/\|PREFIX\|/$prefix/g"
	webots_loadlib -s $settings -c $conf

