#!/bin/bash
set_path=$1
what=$2
value=$3
find $set_path | xargs perl -pi -e "s/.*$what.*\n//g"
find $set_path | xargs perl -pi -e "s/.*<\/setting>\n//g"
echo "   <$what>$value</$what>" >> $set_path 
echo "</setting>" >> $set_path

