#!/bin/bash
LIB_PATH=${A:-/home/efx/.local/usr/lib}
WEBOTS_PATH=${B:-/usr/local/webots644/webots}
#result=`LD_LIBRARY_PATH=$LIB_PATH $WEBOTS_PATH --minimize --mode=fast`
result=`LD_LIBRARY_PATH=$LIB_PATH $WEBOTS_PATH $@`
echo $result

