#!/bin/bash
#for i in {1,6,10};
#for i in {1..10};
for i in 10;
do
	echo "Systematic study of gait $i"
	echo "    noise sensor study on feedback" `date`
	webots_loadlib -s settings_systematic${i}_noiseSensor_fdb.xml -c articleFrontier >/dev/null 2>&1
done
